version: '3.2'

services:
  openkm:
    container_name: openkm
    hostname: openkm
    image: openkm/openkm-ce:6.3.9
    ports:
      - 8095:8080   
    volumes:
      - ./data/server.xml:/opt/tomcat/conf/server.xml
      - ./data/OpenKM.cfg:/opt/tomcat/OpenKM.cfg
      - ./data/OpenKM.xml:/opt/tomcat/OpenKM.xml
      - ./data/repository:/opt/tomcat/repository
      - ./data/import:/import
    environment:
      CATALINA_OPTS: "-Duser.timezone=America/Chicago"
    links:
      - mysql:mysql

  mysql:
    container_name: openkmdb
    hostname: openkmdb
    image: mysql:8.0.13
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_bin
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./data/mysql:/var/lib/mysql
