version: '3'

services:
  influx:
    container_name: influx
    hostname: influx
    image: influxdb
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    volumes:
      - ./influx:/var/lib/influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "2003:2003"

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    restart: always
    volumes:
      - ./grafana/var/lib/grafana:/var/lib/grafana
      - ./grafana/etc/grafana/grafana.ini:/etc/grafana/grafana.ini
        #ports:
    # - "5000:3000"
    environment:
            #  - INSTALL_PLUGINS="http://plugin-domain.com/my-custom-plugin.zip;custom-plugin"      
      - GF_SERVER_DOMAIN="ststats.hamik.net"
